model_name: "RandomForest"
hyperparameters:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
metrics:
  accuracy: 0.92
  f1_score: 0.89
  precision: 0.90
  recall: 0.87